name: "Build workspace"
description: "This action builds the project."

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version-file: ".node-version"
        cache: "yarn"
        cache-dependency-path: "./yarn.lock"

    - name: Install dependencies
      run: yarn install --frozen-lockfile
      shell: bash

    - name: Build io-functions-service-messages
      run: yarn build
      shell: bash
