apiVersion: v2
name: io-functions-service-messages
description: io-functions-service-messages
type: application
version: 0.5.0
appVersion: 0.5.0
dependencies:
  - name: microservice-chart
    version: 1.20.3
    repository: 'https://pagopa.github.io/aks-microservice-chart-blueprint'
