
apiVersion: v2
name: io-functions-service-messages
description: io-functions-service-messages
type: application
version: 1.0.0
appVersion: 1.0.0
dependencies:
- name: microservice-chart
  version: 1.9.0
  repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
