microservice-chart:
  image:
    repository: 'iopcommonacr.azurecr.io/io-functions-service-messages'
    tag: 'latest'
    pullPolicy: Always
    # readinessProbePath: '/api/ready'
    # livenessProbePath: '/api/live'

  namespace: 'messages'

  ingress:
    create: true
    host: 'weubeta.messages.internal.io.pagopa.it' 
    path: '/(.*)'

  resources:
    requests:
      memory: '96Mi'
      cpu: '40m'
    limits:
      memory: '128Mi'
      cpu: '150m'

  autoscaling:
    enable: false
    minReplica: 1
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: 'cpu'
        metricType: 'Utilization/ AverageValue'
        metadata:
          type: 'Utilization/ AverageValue' # Deprecated in favor of trigger.metricType
          value: '60'
  
  envConfig:
    NODE_ENV: 'production'
    APP_NAME: 'io-functions-service-messages'
    COSMOSDB_URI: 'https://io-d-cosmos-free.documents.azure.com:443/'
    COSMOSDB_NAME: 'db'
    MESSAGE_CONTAINER_NAME: 'messages'

  envSecret:
    COSMOSDB_KEY: 'cosmosdb-free-key'
    QueueStorageConnection: 'iopmessagesweubetasvcst-connection-string'
    APPINSIGHTS_INSTRUMENTATIONKEY: 'appinsights-instrumentationkey'

  keyvault:
    name: 'io-p-messages-kv'
    tenantId: '7788edaf-0346-4068-9d79-c868aed15b3d'
