microservice-chart:
  image:
    repository: 'iopcommonacr.azurecr.io/io-functions-service-messages'
    tag: 'latest'
    pullPolicy: Always
    # readinessProbePath: '/api/ready'
    # livenessProbePath: '/api/live'

  namespace: 'messages'

  ingress:
    create: true
    host: 'weuprod02.messages.internal.io.pagopa.it'
    path: '/service-messages/(.*)'

  resources:
    requests:
      memory: '96Mi'
      cpu: '50m'
    limits:
      memory: '256Mi'
      cpu: '200m'

  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          type: Utilization
          value: '60'
  
  envConfig:
    # required
    NODE_ENV: 'production'
    WEBSITE_NODE_DEFAULT_VERSION: '14.16.0'
    WEBSITE_SITE_NAME: 'io-p-weuprod02-functions-service-messages' # required to show cloud role name in application insights
    # app specific
    COSMOSDB_URI: 'https://io-d-cosmos-free.documents.azure.com:443/'
    COSMOSDB_NAME: 'db'
    MESSAGE_CONTAINER_NAME: 'messages'

  envSecret:
    # required
    APPINSIGHTS_INSTRUMENTATIONKEY: 'appinsights-instrumentationkey'
    # app specific
    COSMOSDB_KEY: 'cosmosdb-free-key'
    QueueStorageConnection: 'iopmessagesweuprod02svst-connection-string'

  keyvault:
    name: 'io-p-messages-kv'
    tenantId: '7788edaf-0346-4068-9d79-c868aed15b3d'
