microservice-chart:
  image:
    repository: iopcommonacr.azurecr.io/io-functions-service-messages
    tag: "latest"
    pullPolicy: Always

  namespace: "messages"

  resources:
    requests:
      memory: "96Mi"
      cpu: "40m"
    limits:
      memory: "128Mi"
      cpu: "150m"

  autoscaling:
    minReplica: 1
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metricType: Utilization/ AverageValue
        metadata:
          type: Utilization/ AverageValue # Deprecated in favor of trigger.metricType
          value: "60"
  
  envConfig:
    COSMOSDB_URI: "https://cosmosdb:3000/"
    COSMOSDB_NAME: "db"

  envSecret:
    COSMOSDB_KEY: cosmosdb-free-key

  keyvault:
    name: "io-d-messages-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"