microservice-chart:
  image:
    repository: iopcommonacr.azurecr.io/io-functions-service-messages
    tag: "latest"
    pullPolicy: Always

  namespace: 'messages'
  nameOverride: ''
  fullnameOverride: ''

  serviceAccount:
    create: false
    annotations: {}
    name: ''

  podAnnotations: {}

  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault

  securityContext:
    allowPrivilegeEscalation: false

  resources:
    requests:
      memory: "500Mi"
      cpu: "500m"
    limits:
      memory: "1000Mi"
      cpu: "1100m"

  autoscaling:
    minReplica: 1
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metricType: Utilization/ AverageValue
        metadata:
          type: Utilization/ AverageValue # Deprecated in favor of trigger.metricType
          value: "60"
  
  envConfig:
    COSMOSDB_URI: "https://cosmosdb:3000/"

  envSecret:
    COSMOSDB_KEY: cosmosdb-free-key

  keyvault:
    name: "io-d-messages-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"

  nodeSelector: {}

  tolerations: []

  affinity: {}
