name: "Make workspace artifact"
description: "This action creates an artifact for the selected workspace."

inputs:
  workspace-name:
    description: The name of the workspace to create the artifact for"
    required: true

outputs:
  artifact-path:
    description: The path to the created artifact
    value: ${{ steps[format('make-{0}-artifact', steps.detect-workspace-type.outputs.workspace-type)].outputs.artifact-path }}

runs:
  using: "composite"
  steps:
    - name: Make the azure function app artifact
      id: make-function-app-artifact
      run: |
        npm install --save-dev npm-pack-zip
        npm pkg set --json "bundledDependencies"=true
        npm pkg set --json "files"='["**/function.json", "dist", "host.json","extensions.csproj"]'
        npm-pack-zip
        echo "artifact-path=$(realpath ${{ inputs.workspace-name }}.zip)" >> "$GITHUB_OUTPUT"
      shell: bash
    