name: Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: The type of this release
        required: true
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    name: Bump Version
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@1f9a0c22da41e6ebfa534300ef656657ea2c6707

      - name: Build app
        uses: ./.github/actions/node-yarn

      - name: Release
        id: release
        run: |
          git config user.email "io-pagopa-github-bot@pagopa.it"
          git config user.name "pagopa-github-bot"
          npm version ${{ inputs.release_type }} --no-git-tag-version
          NEXT_VERSION=$(node -p "require('./package.json').version")
          RELEASE_TAG="v$NEXT_VERSION-RELEASE"
          TITLE="Release $NEXT_VERSION"
          git add package.json
          git tag $RELEASE_TAG
          git commit -m "Bump version to $RELEASE_TAG [skip ci]"
          git push origin master && git push --tags
          gh release create $RELEASE_TAG --title $TITLE
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}