name: "Code Review"

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  workflow_dispatch: {}

jobs:
  code_review:
    timeout-minutes: 10 # temp fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Build app
        uses: ./.github/actions/node-yarn

      - name: Lint 
        run: yarn lint
        shell: bash

      - name: Validate Openapi Specs
        run: |
          npx oval validate -p openapi/index.yaml 
          npx oval validate -p openapi/index_external.yaml
        shell: bash

      - name: Unit Tests
        run: |
          yarn generate
          yarn test:coverage
        shell: bash
      
  integration_test:
    timeout-minutes: 10 # temp fix
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      
      - name: Build app
        uses: ./.github/actions/node-yarn

      - name: Start Functions
        run: |
          cd __integrations__
          sed -i 's/FF_TYPE=.*/FF_TYPE=none/g' environments/env.base
          cp environments/env.base environments/.env
          yarn install --frozen-lockfile
          yarn start
        shell: bash
        
      - name: Run Integration Tests
        run: |
          cd __integrations__
          yarn install --frozen-lockfile
          sleep 30s
          docker exec fn-service-messages-testagent yarn test
        shell: bash

      

      

      