name: Deploy (io-p-messages-sending-func)

on:
  workflow_dispatch: {}

jobs:
  deploy_workspace_to_azure:
    name: Deploy
    uses: pagopa/io-std/.github/workflows/deploy-workspace.yaml@main
    with:
      environment: io-p-messages-sending-func
      workspace-name: io-p-messages-sending-func
    secrets: inherit